# -*- coding: utf-8 -*-
"""Untitled70.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qEtV9OWb72qnFMGi9gNxx__La81d3pJr
"""

#First Task
import datetime as dt


def my_func(my_birth = 2000):
  current_dt = dt.datetime.now()
  current_year = current_dt.year
  my_age = current_year - my_birth
  return my_age


def calculated_age():
    my_birth = input("Please enter the year you were born: ")
    try:
        my_birth = int(my_birth)
        age_year = my_func(my_birth)

        return age_year

    except:
        #string
        return my_func()
my_calculated_age = calculated_age()
print(my_calculated_age)

#Second Task
def my_discount(my_price):
  if my_price<100:
    print("there is no discount", end=" ")
    print(my_price)
  elif 100<=my_price<=200:
    print("10% of discount is applied", end=" ")
    my_price = int(my_price*0.9)
    print(my_price)
  elif my_price>200:
    print("20% of discount is applied", end=" ")
    my_price = int(my_price*0.8)
    print(my_price)
my_price=int(input("Please enter the price of your product: "))
my_discount(my_price)