# -*- coding: utf-8 -*-
"""Week3 Task

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pepjwYTPRrSca3H5u5qv0u3VbgWgnRr9
"""

# First Task
""""
my_input = input("Please enter: ")
while my_input != "coder403":
  my_input = input("Please enter: ") 
print(my_input)

"""
while True:
  my_input = input("Please enter: ")
  if my_input=="coder403":
    print(my_input)
    break

# Second Task

# First Version
def  check_password(password):
  my_password = password.strip()
  for char in my_password:
    if char.isupper()==True:
        check = True
        break
    else:
      check = False         
  if check:
    point = False
    for elem in my_password:
      if elem.islower()==True:
        point = True
        break
    if point:
      if any(elem.islower() for elem in my_password): # is True
        if my_password.isalnum(): # is True
          return True
    else:
      return False
  else:
    return False

# Second Version
def  check_password(password):
  my_password = password.strip()
  if any(char.isupper() for char in my_password):
    if any(elem.islower() for elem in my_password): # is True
      if my_password.isalnum(): # is True
        return True
    else:
      return False
  else:
    return False    

# Third Task
email_and_password = input("Input: ") # seperated by space
my_email = email_and_password.split(" ")[0].strip().lower()
my_pass = email_and_password.split(" ")[1]
if check_password(my_pass)==True:
  if my_pass=="Coder403" and my_email=="coder403@yalchin.info":
    print("welcome")
  else:
    print("access denied")
else:
  print("access denied")